### PR TITLE
fix!: use name option to support multiple lsp servers in one test

### LINKED ISSUE #29: GenLSP.Test.server/2 cannot be isolated properly
I faced with it while I wanted to extract tests for hover feature in NextLS to a dedicated test file (as tests in one file and not wrapped in different modules are processing sequentially).
I reached the point when `GenLSP.Buffer` couldn't be started as there is already one existing. But forwarding unique name to it didn't work because the `@options_schema` accepts only `communication`.

After fixing this other isolation problems may arise.

### PR DESCRIPTION
**Pull request by sineed**
closes #29

It should now support having multiple LSP servers started in one test and also to be isolated in async test files.

### CODE REVIEW

File: lib/gen_lsp/buffer.ex [hunk 1]
```diff
@@ -9,10 +9,15 @@ defmodule GenLSP.Buffer do
   @options_schema NimbleOptions.new!(
                     communication: [
                       type: :mod_arg,
-                      default: {GenLSP.Communication.Stdio, []},
```
Comment (mhanberg) [inline lib/gen_lsp/buffer.ex:12]: revert please

File: lib/gen_lsp/buffer.ex [hunk 2]
```diff
@@ -23,8 +28,8 @@ defmodule GenLSP.Buffer do
   #{NimbleOptions.docs(@options_schema)}
   """
   def start_link(opts) do
-    opts = NimbleOptions.validate!(opts, @options_schema)
-    GenServer.start_link(__MODULE__, opts, name: Keyword.get(opts, :name, __MODULE__))
+    init_opts = NimbleOptions.validate!(opts, @options_schema)
+    GenServer.start_link(__MODULE__, init_opts, name: Keyword.get(opts, :name, __MODULE__))
```
Comment (mhanberg) [inline lib/gen_lsp/buffer.ex:32]:
```suggestion
    opts = NimbleOptions.validate!(opts, @options_schema)
    GenServer.start_link(__MODULE__, opts, Keyword.take(opts, [:name]))
```

File: lib/gen_lsp/test.ex [hunk 3]
```diff
@@ -30,12 +30,28 @@ defmodule GenLSP.Test do
...
 
     {:ok, port} = :inet.port(GenLSP.Buffer.comm_state(buffer).lsocket)
 
-    lsp = start_supervised!({mod, Keyword.merge([buffer: buffer], opts)})
+    lsp = start_supervised!(
+      Supervisor.child_spec(
+        {mod, Keyword.merge([buffer: buffer], opts)},
+        id: lsp_id
+      )
+    )
```
Comment (mhanberg) [inline lib/gen_lsp/test.ex:54]: i don't think any of this needs to change

File: test/gen_lsp_test.exs [hunk 4]
```diff
@@ -146,4 +146,12 @@ defmodule GenLSPTest do
...
     })
   end
+
+  test "can start multiple servers in one test/2" do
+    assert %{} = server(GenLSPTest.ExampleServer, name: :example_server_2)
+
+    assert_raise RuntimeError, ~r/more than one child specification has the id: :example_server_2buffer/, fn ->
+      server(GenLSPTest.ExampleServer, name: :example_server_2)
+    end
+  end
```
Comment (mhanberg) [inline test/gen_lsp_test.exs:156]: this test is testing that you can't open 2 with the same name, not that it can start multiple

**Review by mhanberg — CHANGES_REQUESTED** [review]
You should remove this line: https://github.com/elixir-tools/gen_lsp/blob/main/lib/gen_lsp.ex#L123

File: test/gen_lsp_test.exs (hunk 4 above)
Comment (sineed) [reply test/gen_lsp_test.exs:156]: it already started a `server` in the setup

Comment (mhanberg) [reply test/gen_lsp_test.exs:156]: oh, missed that, i don't think you need the assert raise assertion

i would probably assert on if the server is alive then with the `alive?` function.

File: lib/gen_lsp/test.ex (hunk 3 above)
Comment (sineed) [reply lib/gen_lsp/test.ex:54]: Actually not as without specifying `id` I get the following failure:
```elixir
  1) test can start multiple servers in one test/2 (GenLSPTest)
     test/gen_lsp_test.exs:150
     ** (RuntimeError) failed to start child with the spec {GenLSP.Buffer, [communication: {GenLSP.Communication.TCP, [port: 0]}, name: :example_server_2buffer]}.
     Reason: bad child specification, more than one child specification has the id: GenLSP.Buffer.
     If using maps as child specifications, make sure the :id keys are unique.
     If using a module or {module, arg} as child, use Supervisor.child_spec/2 to change the :id, for example:

         children = [
           Supervisor.child_spec({MyWorker, arg}, id: :my_worker_1),
           Supervisor.child_spec({MyWorker, arg}, id: :my_worker_2)
         ]
```

Comment (sineed) [reply lib/gen_lsp/test.ex:54]: Or for the lsp without `id`:

```elixir
  1) test can start multiple servers in one test/2 (GenLSPTest)
     test/gen_lsp_test.exs:150
     ** (RuntimeError) failed to start child with the spec {GenLSPTest.ExampleServer, [buffer: #PID<0.288.0>, name: :example_server_2]}.
     Reason: bad child specification, more than one child specification has the id: GenLSPTest.ExampleServer.
     If using maps as child specifications, make sure the :id keys are unique.
     If using a module or {module, arg} as child, use Supervisor.child_spec/2 to change the :id, for example:

         children = [
           Supervisor.child_spec({MyWorker, arg}, id: :my_worker_1),
           Supervisor.child_spec({MyWorker, arg}, id: :my_worker_2)
         ]
```

Comment (sineed) [reply lib/gen_lsp/test.ex:54]: you can see in the NextLS PR that I had to specify this `id` in most of processes to make it work

Comment (mhanberg) [reply lib/gen_lsp/test.ex:54]: I think this is only happening because you are starting them under the same test supervisor, i don't think you'll ever be starting two LSPs in one test.

Comment (sineed) [reply lib/gen_lsp/test.ex:54]: I actually did it in the new test for NextLS 🙉

File: test/gen_lsp_test.exs (hunk 4 above)
Comment (sineed) [reply test/gen_lsp_test.exs]: addressed

File: lib/gen_lsp/buffer.ex (hunk 1 above)
Comment (sineed) [reply lib/gen_lsp/buffer.ex:12]: reverted here and removed in `GenLSP`

File: lib/gen_lsp/buffer.ex (hunk 2 above)
Comment (sineed) [reply lib/gen_lsp/buffer.ex]: applied
